create_project -force -part xc7a35t-csg324-1 fpga
add_files -fileset sources_1 defines.v
add_files -fileset sources_1 ../rtl/fpga.v
add_files -fileset sources_1 ../rtl/fpga_core.v
add_files -fileset sources_1 ../rtl/debounce_switch.v
add_files -fileset sources_1 ../rtl/sync_signal.v
add_files -fileset sources_1 ../lib/eth/rtl/ssio_sdr_in.v
add_files -fileset sources_1 ../lib/eth/rtl/mii_phy_if.v
add_files -fileset sources_1 ../lib/eth/rtl/eth_mac_mii_fifo.v
add_files -fileset sources_1 ../lib/eth/rtl/eth_mac_mii.v
add_files -fileset sources_1 ../lib/eth/rtl/eth_mac_1g.v
add_files -fileset sources_1 ../lib/eth/rtl/axis_gmii_rx.v
add_files -fileset sources_1 ../lib/eth/rtl/axis_gmii_tx.v
add_files -fileset sources_1 ../lib/eth/rtl/lfsr.v
add_files -fileset sources_1 ../lib/eth/rtl/eth_axis_rx.v
add_files -fileset sources_1 ../lib/eth/rtl/eth_axis_tx.v
add_files -fileset sources_1 ../lib/eth/rtl/udp_complete.v
add_files -fileset sources_1 ../lib/eth/rtl/udp_checksum_gen.v
add_files -fileset sources_1 ../lib/eth/rtl/udp.v
add_files -fileset sources_1 ../lib/eth/rtl/udp_ip_rx.v
add_files -fileset sources_1 ../lib/eth/rtl/udp_ip_tx.v
add_files -fileset sources_1 ../lib/eth/rtl/ip_complete.v
add_files -fileset sources_1 ../lib/eth/rtl/ip.v
add_files -fileset sources_1 ../lib/eth/rtl/ip_eth_rx.v
add_files -fileset sources_1 ../lib/eth/rtl/ip_eth_tx.v
add_files -fileset sources_1 ../lib/eth/rtl/ip_arb_mux.v
add_files -fileset sources_1 ../lib/eth/rtl/arp.v
add_files -fileset sources_1 ../lib/eth/rtl/arp_cache.v
add_files -fileset sources_1 ../lib/eth/rtl/arp_eth_rx.v
add_files -fileset sources_1 ../lib/eth/rtl/arp_eth_tx.v
add_files -fileset sources_1 ../lib/eth/rtl/eth_arb_mux.v
add_files -fileset sources_1 ../lib/eth/lib/axis/rtl/arbiter.v
add_files -fileset sources_1 ../lib/eth/lib/axis/rtl/priority_encoder.v
add_files -fileset sources_1 ../lib/eth/lib/axis/rtl/axis_fifo.v
add_files -fileset sources_1 ../lib/eth/lib/axis/rtl/axis_async_fifo.v
add_files -fileset sources_1 ../lib/eth/lib/axis/rtl/axis_async_fifo_adapter.v
add_files -fileset sources_1 ../lib/eth/lib/axis/rtl/sync_reset.v
add_files -fileset constrs_1 ../fpga.xdc
add_files -fileset constrs_1 ../lib/eth/syn/vivado/mii_phy_if.tcl
add_files -fileset constrs_1 ../lib/eth/syn/vivado/eth_mac_fifo.tcl
add_files -fileset constrs_1 ../lib/eth/lib/axis/syn/vivado/axis_async_fifo.tcl
add_files -fileset constrs_1 ../lib/eth/lib/axis/syn/vivado/sync_reset.tcl
exit
